### ISSUE TITLE
Autoroles: filter bot accounts

### ISSUE THREAD

**Issue by 0x5c** [0x5c/minibot#17]

**Comment by classabbyamp** [comment]
idea: add a per-guild key for whether or not to auto-role bots. this will be easier with bolt per-guild config system (maybe hold off until then?)

**Comment by 0x5c** [comment]
This could be added as-is; we would just need to make this change:
```py
Dict[int, List[int]]
Dict[int, Tuple[List[int], bool]]
```
But I believe that it is unnecessary; when adding a bot to a server, you manually apply one or more bot roles anyway.
